# Generated by Django 3.2.25 on 2026-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='logo',
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
